services:
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./backend/database.db:/home/OpinioNet/backend/database.db

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"